baseURL = "https://kaleidoeye.org/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Kaleidoeye"                        # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 7                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码

rssLimit = 7                          # RSS生成文章数量

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "奂目"

[blackfriday]
  smartypants = false

[menu]
  main = [
      {name = "主页", Weight = 1, identifier = "home", url = "/"},
      {name = "标签", Weight = 2, identifier = "tags", url = "/tags/"},
      {name = "分类", Weight = 3, identifier = "categories", url = "/categories/"},
      {name = "归档", Weight = 4, identifier = "archive", url = "/posts/"},
      {name = "关于", Weight = 5, identifier = "about", url = "/about/"}
  ]

[params]
  subTitle = ""                                       # site's subTitle              # 网站二级标题
  footerSlogan = ""                                   # site's footer slogan         # 网站页脚标语
  keywords = ["kaleidoeye","奂目","博客"]                                   # site's keywords              # 网站关键字
  description = ""                        # site's description           # 网站描述
#  enableMathJax = false                                                # enable mathjax               # 是否使用mathjax（数学公式）
#  enablemode = false
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","translations"]
  fancybox = true       # 图片放大功能

[params.footer]
  powered_by = 'Copyright © Kaleidoeye 2022'
  Slogan = ""                                   # site's footer slogan 
  
[params.twikoo]
  enable = true
  envId = 'https://twikoo.kaleidoeye.org/'
  twikoojs = 'https://cdn.jsdelivr.net/npm/twikoo@1.6.7/dist/twikoo.min.js'  
  
# Your socail's url
# 社交地址配置
[social]
  github = ""
  twitter = ""
  facebook = ""
  weibo = ""
  instagram = ""

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
  